---
abstract: 'Retrieve learning objectives from Achievement Standards Network'
author:
  - 'Mark A. Stratman, C<< <stratman at gmail.com> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  File::Spec::Functions: 0
  FindBin: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-ASN
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  File::Slurp: 0
  JSON: 0
  LWP::Simple: 0
  Moo: 1
  URI: 0
  XML::Twig: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/mstratman/WWW-ASN.git
version: 0.01
